export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_DELETE_ALL = "PRODUCT_DELETE_ALL";
export const PRODUCT_FETCH_ALL = "PRODUCT_FETCH_ALL";
